import type {
  AccountingEntry,
  CategoryShare,
  PlatformShare,
  WeeklyRevenuePoint,
} from "@/types/maat";

export const weeklyKpi = {
  revenueCents: 268000,
  revenueDeltaPct: 14.5,
  revenueDeltaCents: 34000,
  unitsSold: 21,
  unitsDeltaPct: 16.7,
  unitsPrevWeek: 18,
  avgPriceCents: 12800,
  avgPriceDeltaPct: 2.4,
  avgPriceMinCents: 4100,
  avgPriceMaxCents: 22800,
  netCents: 219000,
  netMarginPct: 81.7,
};

export const topCategory = {
  name: "Giacche & capispalla",
  runnerUp: "Felpe & maglieria",
  runnerUpSharePct: 23,
  revenueCents: 398000,
  units: 24,
  sharePct: 35,
  deltaPct: 12,
};

export const weeklyRevenue: WeeklyRevenuePoint[] = [
  { weekLabel: "25/5", revenueCents: 118000, unitsSold: 9 },
  { weekLabel: "1/6", revenueCents: 152000, unitsSold: 12 },
  { weekLabel: "8/6", revenueCents: 134000, unitsSold: 10 },
  { weekLabel: "15/6", revenueCents: 176000, unitsSold: 14 },
  { weekLabel: "22/6", revenueCents: 201000, unitsSold: 16 },
  { weekLabel: "29/6", revenueCents: 189000, unitsSold: 15 },
  { weekLabel: "6/7", revenueCents: 234000, unitsSold: 18 },
  { weekLabel: "13/7", revenueCents: 268000, unitsSold: 21, current: true },
];

export const platformShares: PlatformShare[] = [
  { marketplace: "vinted", revenueCents: 482000, sales: 51 },
  { marketplace: "depop", revenueCents: 276000, sales: 29 },
  { marketplace: "grailed", revenueCents: 184000, sales: 12 },
  { marketplace: "vestiaire", revenueCents: 115000, sales: 9 },
  { marketplace: "ebay", revenueCents: 92000, sales: 19 },
];

export const categoryShares: CategoryShare[] = [
  { category: "Giacche & capispalla", revenueCents: 398000, units: 24 },
  { category: "Felpe & maglieria", revenueCents: 264000, units: 31 },
  { category: "Denim", revenueCents: 172000, units: 18 },
  { category: "Sneakers & scarpe", revenueCents: 149000, units: 11 },
  { category: "T-shirt & camicie", revenueCents: 98000, units: 22 },
  { category: "Accessori", revenueCents: 68000, units: 14 },
];

export const cassaSettlement = {
  totalCents: 1149000,
  liquidatoCents: 879000,
  payoutInArrivoCents: 176000,
  payoutEta: "21 lug",
  inEscrowCents: 94000,
  escrowFinestraGiorni: 14,
};

export const cassaKpi = {
  commissioniCents: 32200,
  commissioniPctVenduto: 12,
  spedizioniCents: 16800,
  spedizioniCount: 21,
  spedizioniMediaCents: 800,
  inEscrowCents: 94000,
  inEscrowSales: 6,
  payoutPrevistoCents: 176000,
  payoutEta: "21 lug",
};

export const accountingEntries: AccountingEntry[] = [
  {
    id: "tx-1",
    eventDate: "2026-07-13",
    itemLabel: "Stone Island · Bomber",
    category: "Giacche & capispalla",
    marketplace: "vinted",
    entryType: "sale",
    status: "confirmed",
    grossAmountCents: 17200,
    platformFeeCents: 2100,
    shippingCostCents: 800,
    netAmountCents: 14300,
  },
  {
    id: "tx-2",
    eventDate: "2026-07-13",
    itemLabel: "Burberry · Trench",
    category: "Giacche & capispalla",
    marketplace: "grailed",
    entryType: "sale",
    status: "escrow",
    grossAmountCents: 22800,
    platformFeeCents: 2700,
    shippingCostCents: 0,
    netAmountCents: 20100,
  },
  {
    id: "tx-3",
    eventDate: "2026-07-12",
    itemLabel: "The North Face · Nuptse 700",
    category: "Giacche & capispalla",
    marketplace: "vinted",
    entryType: "sale",
    status: "pending",
    grossAmountCents: 15000,
    platformFeeCents: 1800,
    shippingCostCents: 700,
    netAmountCents: 12500,
  },
  {
    id: "tx-4",
    eventDate: "2026-07-12",
    itemLabel: "Nike · Hoodie vintage",
    category: "Felpe & maglieria",
    marketplace: "depop",
    entryType: "sale",
    status: "confirmed",
    grossAmountCents: 5200,
    platformFeeCents: 600,
    shippingCostCents: 500,
    netAmountCents: 4100,
  },
  {
    id: "tx-5",
    eventDate: "2026-07-11",
    itemLabel: "Acne Studios · Maglione lana",
    category: "Felpe & maglieria",
    marketplace: "vestiaire",
    entryType: "sale",
    status: "confirmed",
    grossAmountCents: 11500,
    platformFeeCents: 1800,
    shippingCostCents: 600,
    netAmountCents: 9100,
  },
  {
    id: "tx-6",
    eventDate: "2026-07-11",
    itemLabel: "Levi's · Giacca denim",
    category: "Denim",
    marketplace: "depop",
    entryType: "sale",
    status: "escrow",
    grossAmountCents: 6800,
    platformFeeCents: 800,
    shippingCostCents: 500,
    netAmountCents: 5500,
  },
  {
    id: "tx-7",
    eventDate: "2026-07-10",
    itemLabel: "Dr. Martens · 1460",
    category: "Sneakers & scarpe",
    marketplace: "depop",
    entryType: "sale",
    status: "confirmed",
    grossAmountCents: 8800,
    platformFeeCents: 1000,
    shippingCostCents: 600,
    netAmountCents: 7200,
  },
];
