import type { CatalogEntry, Notification } from "@/types/maat";

function entry(partial: Pick<CatalogEntry, "id" | "status" | "createdAt" | "attributes"> & { measures?: CatalogEntry["measures"] }): CatalogEntry {
  return {
    sku: partial.status === "available" ? `MAAT-${partial.id.toUpperCase()}` : null,
    accountId: "acc-federico",
    measures: {},
    photos: [
      {
        id: `${partial.id}-p1`,
        label: "fronte",
        url: null,
        photoType: "standard",
        state: "validated",
        createdAt: partial.createdAt,
      },
    ],
    ...partial,
  };
}

export const mockCatalogEntries: CatalogEntry[] = [
  entry({
    id: "b-09",
    status: "to_be_reviewed",
    createdAt: "2026-07-04T09:12:00.000Z",
    attributes: {
      brand: "Stone Island",
      tipoCapo: "Giacca",
      colore: "Verde oliva",
      taglia: "L",
      materiale: "Nylon Ripstop",
      genere: "Uomo",
      condizioni: "",
      difetti: "Nessuno visibile",
      stile: "Sportswear",
      stagionalita: "Mezza stagione",
    },
    measures: { spalle: 46, lunghezzaTotale: 71, lunghezzaManica: 64, larghezzaManica: 18, larghezzaTorace: 58, larghezzaVita: 54 },
  }),
  entry({
    id: "b-08",
    status: "available",
    createdAt: "2026-07-03T14:20:00.000Z",
    attributes: {
      brand: "Levi's",
      tipoCapo: "501 Jeans",
      colore: "Blu denim",
      taglia: "32/34",
      materiale: "Cotone",
      genere: "Uomo",
      condizioni: "Buone",
      difetti: "Nessuno visibile",
      stile: "Casual",
      stagionalita: "Tutte le stagioni",
    },
    measures: { larghezzaVita: 42, larghezzaFianchi: 48, lunghezzaTotale: 108, cavallo: 30, larghezzaCoscia: 30, larghezzaCaviglia: 18 },
  }),
  entry({
    id: "b-07",
    status: "local_draft",
    createdAt: "2026-07-03T08:05:00.000Z",
    attributes: {
      brand: "Nike",
      tipoCapo: "Windbreaker",
      colore: "Nero",
      taglia: "M",
      materiale: "Poliestere",
      genere: "Uomo",
      condizioni: "Da verificare",
      difetti: "Sconosciuti",
      stile: "Sportswear",
      stagionalita: "Mezza stagione",
    },
    measures: { spalle: 44, lunghezzaTotale: 68, lunghezzaManica: 60, larghezzaManica: 20, larghezzaTorace: 56, larghezzaVita: 52 },
  }),
  entry({
    id: "b-06",
    status: "available",
    createdAt: "2026-07-01T11:40:00.000Z",
    attributes: {
      brand: "Barbour",
      tipoCapo: "Beaufort",
      colore: "Verde oliva",
      taglia: "46",
      materiale: "Cotone cerato",
      genere: "Uomo",
      condizioni: "Buone, segni d'uso",
      difetti: "Segni di cera",
      stile: "Country",
      stagionalita: "Autunno/Inverno",
    },
    measures: { spalle: 48, lunghezzaTotale: 74, lunghezzaManica: 66, larghezzaManica: 19, larghezzaTorace: 60, larghezzaVita: 56 },
  }),
  entry({
    id: "b-05",
    status: "to_be_reviewed",
    createdAt: "2026-06-30T16:15:00.000Z",
    attributes: {
      brand: "Carhartt WIP",
      tipoCapo: "Chore Coat",
      colore: "Marrone",
      taglia: "XL",
      materiale: "Cotone canvas",
      genere: "Unisex",
      condizioni: "Ottime",
      difetti: "Nessuno visibile",
      stile: "Workwear",
      stagionalita: "Autunno/Inverno",
    },
    measures: { spalle: 50, lunghezzaTotale: 76, lunghezzaManica: 62, larghezzaManica: 22, larghezzaTorace: 64, larghezzaVita: 60 },
  }),
  entry({
    id: "b-04",
    status: "local_draft",
    createdAt: "2026-06-29T10:30:00.000Z",
    attributes: {
      brand: "Patagonia",
      tipoCapo: "Retro-X Fleece",
      colore: "Beige",
      taglia: "S",
      materiale: "Pile",
      genere: "Donna",
      condizioni: "Buone",
      difetti: "Nessuno visibile",
      stile: "Outdoor",
      stagionalita: "Autunno/Inverno",
    },
    measures: { spalle: 40, lunghezzaTotale: 60, lunghezzaManica: 58, larghezzaManica: 16, larghezzaTorace: 50, larghezzaVita: 48 },
  }),
];

export const mockCatalogEntry: CatalogEntry = {
  id: "b-09",
  sku: null,
  status: "to_be_reviewed",
  accountId: "acc-federico",
  createdAt: "2026-07-04T09:12:00.000Z",
  attributes: {
    brand: "Stone Island",
    tipoCapo: "Giacca",
    colore: "Verde oliva",
    taglia: "L",
    materiale: "Nylon Ripstop",
    genere: "Uomo",
    condizioni: "",
    difetti: "Nessuno visibile",
    stile: "Sportswear",
    stagionalita: "Mezza stagione",
  },
  measures: {
    spalle: 46,
    lunghezzaTotale: 71,
    lunghezzaManica: 64,
    larghezzaManica: 18,
    larghezzaTorace: 58,
    larghezzaVita: 54,
  },
  photos: [
    {
      id: "p1",
      label: "fronte",
      url: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600",
      photoType: "standard",
      state: "validated",
      createdAt: "2026-07-04T09:10:00.000Z",
    },
    {
      id: "p2",
      label: "retro",
      url: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600",
      photoType: "standard",
      state: "validated",
      createdAt: "2026-07-04T09:10:30.000Z",
    },
    {
      id: "p3",
      label: "brand",
      url: null,
      photoType: "standard",
      state: "rejected",
      qualityFlags: ["Sfocata, riprova"],
      createdAt: "2026-07-04T09:11:00.000Z",
    },
  ],
};

/** Lookup per id con fallback al mock canonico. Usato dalla route piena `[id]` e dall'overlay intercettato. */
export function getCatalogEntry(id: string): CatalogEntry {
  return mockCatalogEntries.find((e) => e.id === id) ?? mockCatalogEntry;
}

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    tipo: "draft_ready",
    messaggio: "Stone Island — Giacca pronta per la revisione",
    timestamp: "2026-07-07T13:40:00.000Z",
    letta: false,
    catalogEntryId: "b-09",
  },
  {
    id: "n2",
    tipo: "local_save",
    messaggio: "Nike — Windbreaker salvato in locale, in attesa di sync",
    timestamp: "2026-07-07T12:30:00.000Z",
    letta: false,
    catalogEntryId: "b-07",
  },
  {
    id: "n3",
    tipo: "draft_ready",
    messaggio: "Patagonia — Retro-X Fleece pronto per la revisione",
    timestamp: "2026-07-05T09:00:00.000Z",
    letta: false,
    catalogEntryId: "b-04",
  },
  {
    id: "n4",
    tipo: "draft_ready",
    messaggio: "Carhartt WIP — Chore Coat pronto per la revisione",
    timestamp: "2026-07-04T16:15:00.000Z",
    letta: true,
    catalogEntryId: "b-05",
  },
  {
    id: "n5",
    tipo: "local_save",
    messaggio: "Barbour — Beaufort salvato in locale",
    timestamp: "2026-07-03T11:40:00.000Z",
    letta: true,
    catalogEntryId: "b-06",
  },
  {
    id: "n6",
    tipo: "draft_ready",
    messaggio: "Levi's — 501 Jeans pronto per la revisione",
    timestamp: "2026-07-02T14:20:00.000Z",
    letta: true,
    catalogEntryId: "b-08",
  },
  {
    // Dead-link demo: capo eliminato dopo la creazione della notifica.
    id: "n7",
    tipo: "draft_ready",
    messaggio: "Diesel — Giubbotto pronto per la revisione",
    timestamp: "2026-07-01T09:00:00.000Z",
    letta: true,
    catalogEntryId: "b-99",
  },
];
