import type { Lot, Supplier } from "@/types/maat";

export const suppliers: Supplier[] = [
  { id: "sup-1", name: "Grossista Prato", loadsCount: 12, pieces: 0, kg: 640, updatedAt: "15 lug" },
  { id: "sup-2", name: "Stock Milano", loadsCount: 8, pieces: 1240, kg: 0, updatedAt: "9 lug" },
  { id: "sup-3", name: "Riciclo Tessile Sud", loadsCount: 5, pieces: 0, kg: 380, updatedAt: "2 lug" },
  { id: "sup-4", name: "Vintage Wholesale NL", loadsCount: 3, pieces: 210, kg: 120, updatedAt: "28 giu" },
];

export const CARICO_CATEGORIES = [
  "Mista (categorie assortite)",
  "Giacche & capispalla",
  "Felpe & maglieria",
  "Denim",
  "Sneakers & scarpe",
  "T-shirt & camicie",
  "Accessori",
] as const;

// Storico carichi ricevuti dai fornitori (sezione "Storico carichi" in Contabilità).
// Prezzi coerenti col mockup: totale 3.420 € sugli ultimi 90gg.
export const loadHistory: Lot[] = [
  {
    id: "load-0142",
    code: "CAR-0142",
    name: "CAR-0142",
    supplierName: "Grossista Prato",
    acquiredAt: "2026-07-15",
    executedAt: "2026-07-15",
    type: "ingrosso",
    quantity: 45,
    category: "Giacche & capispalla",
    allocationMethod: "weight_based",
    totalCostCents: null,
    pricePaidCents: 62000,
  },
  {
    id: "load-0141",
    code: "CAR-0141",
    name: "CAR-0141",
    supplierName: "Stock Milano",
    acquiredAt: "2026-07-12",
    executedAt: "2026-07-12",
    type: "pezzo",
    quantity: 60,
    category: "Felpe & maglieria",
    allocationMethod: "uniform",
    totalCostCents: null,
    pricePaidCents: 54000,
  },
  {
    id: "load-0140",
    code: "CAR-0140",
    name: "CAR-0140",
    supplierName: "Stock Milano",
    acquiredAt: "2026-07-09",
    executedAt: "2026-07-09",
    type: "pezzo",
    quantity: 80,
    category: "Mista (categorie assortite)",
    allocationMethod: "uniform",
    totalCostCents: null,
    pricePaidCents: 72000,
  },
  {
    id: "load-0139",
    code: "CAR-0139",
    name: "CAR-0139",
    supplierName: "Riciclo Tessile Sud",
    acquiredAt: "2026-07-02",
    executedAt: "2026-07-02",
    type: "ingrosso",
    quantity: 30,
    category: "Denim",
    allocationMethod: "weight_based",
    totalCostCents: null,
    pricePaidCents: 30000,
  },
  {
    id: "load-0138",
    code: "CAR-0138",
    name: "CAR-0138",
    supplierName: "Vintage Wholesale NL",
    acquiredAt: "2026-06-28",
    executedAt: "2026-06-28",
    type: "pezzo",
    quantity: 24,
    category: "Sneakers & scarpe",
    allocationMethod: "uniform",
    totalCostCents: null,
    pricePaidCents: 96000,
  },
  {
    id: "load-0137",
    code: "CAR-0137",
    name: "CAR-0137",
    supplierName: "Grossista Prato",
    acquiredAt: "2026-06-21",
    executedAt: "2026-06-21",
    type: "pezzo",
    quantity: 40,
    category: "Accessori",
    allocationMethod: "uniform",
    totalCostCents: null,
    pricePaidCents: 28000,
  },
];
